schema : schema.graphql
extensions :
  endpoints :
    Default GraphQL Endpoint :
      url : http://localhost:8080/airlineManagement

      headers :
        user-agent : JS GraphQL
      introspect : false
  exception-handlers-enabled: true